require("brimalval.core.keymaps")
require("brimalval.core.filetypes")
require("brimalval.core.options")
require("brimalval.core.autocmds")
require("brimalval.core.highlights")
require("brimalval.core.utils")
